// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/server/server.proto

package server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ScenarioDesc struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ArtifactoryUrl       string   `protobuf:"bytes,2,opt,name=ArtifactoryUrl,proto3" json:"ArtifactoryUrl,omitempty"`
	ApiKey               string   `protobuf:"bytes,3,opt,name=ApiKey,proto3" json:"ApiKey,omitempty"`
	MinSize              int32    `protobuf:"varint,4,opt,name=MinSize,proto3" json:"MinSize,omitempty"`
	MaxSize              int32    `protobuf:"varint,5,opt,name=MaxSize,proto3" json:"MaxSize,omitempty"`
	NbFiles              int32    `protobuf:"varint,6,opt,name=NbFiles,proto3" json:"NbFiles,omitempty"`
	NbThreads            int32    `protobuf:"varint,7,opt,name=NbThreads,proto3" json:"NbThreads,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScenarioDesc) Reset()         { *m = ScenarioDesc{} }
func (m *ScenarioDesc) String() string { return proto.CompactTextString(m) }
func (*ScenarioDesc) ProtoMessage()    {}
func (*ScenarioDesc) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_06688ce1a6abb261, []int{0}
}
func (m *ScenarioDesc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScenarioDesc.Unmarshal(m, b)
}
func (m *ScenarioDesc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScenarioDesc.Marshal(b, m, deterministic)
}
func (dst *ScenarioDesc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScenarioDesc.Merge(dst, src)
}
func (m *ScenarioDesc) XXX_Size() int {
	return xxx_messageInfo_ScenarioDesc.Size(m)
}
func (m *ScenarioDesc) XXX_DiscardUnknown() {
	xxx_messageInfo_ScenarioDesc.DiscardUnknown(m)
}

var xxx_messageInfo_ScenarioDesc proto.InternalMessageInfo

func (m *ScenarioDesc) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ScenarioDesc) GetArtifactoryUrl() string {
	if m != nil {
		return m.ArtifactoryUrl
	}
	return ""
}

func (m *ScenarioDesc) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *ScenarioDesc) GetMinSize() int32 {
	if m != nil {
		return m.MinSize
	}
	return 0
}

func (m *ScenarioDesc) GetMaxSize() int32 {
	if m != nil {
		return m.MaxSize
	}
	return 0
}

func (m *ScenarioDesc) GetNbFiles() int32 {
	if m != nil {
		return m.NbFiles
	}
	return 0
}

func (m *ScenarioDesc) GetNbThreads() int32 {
	if m != nil {
		return m.NbThreads
	}
	return 0
}

type Response struct {
	StatusCode           int32    `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_06688ce1a6abb261, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func init() {
	proto.RegisterType((*ScenarioDesc)(nil), "ScenarioDesc")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() { proto.RegisterFile("proto/server/server.proto", fileDescriptor_server_06688ce1a6abb261) }

var fileDescriptor_server_06688ce1a6abb261 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xd0, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x06, 0x60, 0x13, 0x4d, 0x6a, 0x86, 0xb6, 0x87, 0x3d, 0xc8, 0x2a, 0x22, 0x25, 0x07, 0x29,
	0x3d, 0x44, 0xd0, 0xa3, 0xa7, 0xa2, 0x78, 0x51, 0x8b, 0x24, 0xfa, 0x00, 0x9b, 0xdd, 0x11, 0x07,
	0x4a, 0x36, 0xec, 0x6e, 0xc5, 0xfa, 0x88, 0x3e, 0x95, 0x38, 0x4d, 0x30, 0xf4, 0xb4, 0xfc, 0xff,
	0x07, 0x0b, 0xf3, 0xc3, 0x69, 0xeb, 0x6c, 0xb0, 0x57, 0x1e, 0xdd, 0x27, 0xba, 0xee, 0x29, 0xb8,
	0xcb, 0x7f, 0x22, 0x18, 0x57, 0x1a, 0x1b, 0xe5, 0xc8, 0xde, 0xa3, 0xd7, 0x62, 0x0a, 0x31, 0x19,
	0x19, 0xcd, 0xa2, 0x79, 0x56, 0xc6, 0x64, 0xc4, 0x25, 0x4c, 0x97, 0x2e, 0xd0, 0xbb, 0xd2, 0xc1,
	0xba, 0xed, 0x9b, 0x5b, 0xcb, 0x98, 0x6d, 0xaf, 0x15, 0x27, 0x90, 0x2e, 0x5b, 0x7a, 0xc4, 0xad,
	0x3c, 0x64, 0xef, 0x92, 0x90, 0x30, 0x7a, 0xa6, 0xa6, 0xa2, 0x6f, 0x94, 0x47, 0xb3, 0x68, 0x9e,
	0x94, 0x7d, 0x64, 0x51, 0x5f, 0x2c, 0x49, 0x27, 0xbb, 0xf8, 0x27, 0xab, 0xfa, 0x81, 0xd6, 0xe8,
	0x65, 0xba, 0x93, 0x2e, 0x8a, 0x73, 0xc8, 0x56, 0xf5, 0xeb, 0x87, 0x43, 0x65, 0xbc, 0x1c, 0xb1,
	0xfd, 0x17, 0xf9, 0x02, 0x8e, 0x4b, 0xf4, 0xad, 0x6d, 0x3c, 0x8a, 0x0b, 0x00, 0x1f, 0x54, 0xd8,
	0xf8, 0x3b, 0x6b, 0x90, 0xef, 0x49, 0xca, 0x41, 0x73, 0x7d, 0x0b, 0x93, 0x17, 0xd2, 0xed, 0x46,
	0x63, 0xc5, 0x7b, 0x88, 0x05, 0x8c, 0x9f, 0xac, 0x32, 0xfd, 0x18, 0x62, 0x52, 0x0c, 0x77, 0x39,
	0xcb, 0x8a, 0xfe, 0xeb, 0xfc, 0xa0, 0x4e, 0x79, 0xbc, 0x9b, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x01, 0x43, 0x1f, 0xb6, 0x59, 0x01, 0x00, 0x00,
}
