build:
	protoc -I. --micro_out=$(GOPATH)/src/github.com/jroquelaure/picpuce/picpuce-scenario-runner --go_out=$(GOPATH)/src/github.com/jroquelaure/picpuce/picpuce-scenario-runner \
	  proto/runner/runner.proto