apiVersion: v1
kind: Service
metadata:
  name: picpuce-server
  labels:
    app: picpuce-server
spec:
  ports:
  - name: picpuce-server
    port: 8080
    targetPort: 8080
  clusterIP: None
  selector:
    role: picpuce-server