// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/runner/runner.proto

package runner

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Scenario struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ArtifactoryUrl       string   `protobuf:"bytes,2,opt,name=artifactoryUrl,proto3" json:"artifactoryUrl,omitempty"`
	ApiKey               string   `protobuf:"bytes,3,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	Done                 bool     `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Scenario) Reset()         { *m = Scenario{} }
func (m *Scenario) String() string { return proto.CompactTextString(m) }
func (*Scenario) ProtoMessage()    {}
func (*Scenario) Descriptor() ([]byte, []int) {
	return fileDescriptor_runner_af6279a3fca9739d, []int{0}
}
func (m *Scenario) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Scenario.Unmarshal(m, b)
}
func (m *Scenario) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Scenario.Marshal(b, m, deterministic)
}
func (dst *Scenario) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scenario.Merge(dst, src)
}
func (m *Scenario) XXX_Size() int {
	return xxx_messageInfo_Scenario.Size(m)
}
func (m *Scenario) XXX_DiscardUnknown() {
	xxx_messageInfo_Scenario.DiscardUnknown(m)
}

var xxx_messageInfo_Scenario proto.InternalMessageInfo

func (m *Scenario) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Scenario) GetArtifactoryUrl() string {
	if m != nil {
		return m.ArtifactoryUrl
	}
	return ""
}

func (m *Scenario) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *Scenario) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

type Chunk struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	FileId               string   `protobuf:"bytes,3,opt,name=fileId,proto3" json:"fileId,omitempty"`
	ScenarioId           string   `protobuf:"bytes,4,opt,name=scenarioId,proto3" json:"scenarioId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_runner_af6279a3fca9739d, []int{1}
}
func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk.Unmarshal(m, b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
}
func (dst *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(dst, src)
}
func (m *Chunk) XXX_Size() int {
	return xxx_messageInfo_Chunk.Size(m)
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Chunk) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Chunk) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func (m *Chunk) GetScenarioId() string {
	if m != nil {
		return m.ScenarioId
	}
	return ""
}

type Response struct {
	StatusCode           int32    `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	TotalTransferTime    int32    `protobuf:"varint,2,opt,name=totalTransferTime,proto3" json:"totalTransferTime,omitempty"`
	TotalContentSize     int32    `protobuf:"varint,3,opt,name=totalContentSize,proto3" json:"totalContentSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_runner_af6279a3fca9739d, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *Response) GetTotalTransferTime() int32 {
	if m != nil {
		return m.TotalTransferTime
	}
	return 0
}

func (m *Response) GetTotalContentSize() int32 {
	if m != nil {
		return m.TotalContentSize
	}
	return 0
}

func init() {
	proto.RegisterType((*Scenario)(nil), "Scenario")
	proto.RegisterType((*Chunk)(nil), "Chunk")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() { proto.RegisterFile("proto/runner/runner.proto", fileDescriptor_runner_af6279a3fca9739d) }

var fileDescriptor_runner_af6279a3fca9739d = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xc1, 0x4a, 0xfb, 0x40,
	0x10, 0xc6, 0xff, 0xe9, 0xbf, 0x89, 0xc9, 0x28, 0x45, 0xf7, 0x20, 0xd1, 0x83, 0xd4, 0x80, 0x52,
	0x44, 0x22, 0xe8, 0x13, 0x48, 0x4e, 0xc5, 0xdb, 0xb6, 0x3e, 0xc0, 0x9a, 0x9d, 0xe0, 0x62, 0x9c,
	0x0d, 0x9b, 0xcd, 0xa1, 0x9e, 0x7d, 0x70, 0x71, 0x92, 0x48, 0x35, 0xa7, 0x9d, 0xf9, 0xcd, 0x30,
	0xdf, 0xc7, 0xb7, 0x70, 0xd6, 0x38, 0xeb, 0xed, 0x9d, 0xeb, 0x88, 0xd0, 0x0d, 0x4f, 0xce, 0x2c,
	0x23, 0x88, 0x37, 0x25, 0x92, 0x72, 0xc6, 0x8a, 0x05, 0xcc, 0x8c, 0x4e, 0x83, 0x65, 0xb0, 0x4a,
	0xe4, 0xcc, 0x68, 0x71, 0x0d, 0x0b, 0xe5, 0xbc, 0xa9, 0x54, 0xe9, 0xad, 0xdb, 0x3d, 0xbb, 0x3a,
	0x9d, 0xf1, 0xec, 0x0f, 0x15, 0xa7, 0x10, 0xa9, 0xc6, 0x3c, 0xe1, 0x2e, 0xfd, 0xcf, 0xf3, 0xa1,
	0x13, 0x02, 0xe6, 0xda, 0x12, 0xa6, 0xf3, 0x65, 0xb0, 0x8a, 0x25, 0xd7, 0x99, 0x81, 0xb0, 0x78,
	0xed, 0xe8, 0x6d, 0x22, 0x96, 0xc2, 0x41, 0x69, 0xc9, 0x23, 0x79, 0x56, 0x39, 0x92, 0x63, 0xfb,
	0x7d, 0xbe, 0x32, 0x35, 0xae, 0xf5, 0x78, 0xbe, 0xef, 0xc4, 0x05, 0x40, 0x3b, 0x58, 0x5f, 0x6b,
	0x16, 0x49, 0xe4, 0x1e, 0xc9, 0x3e, 0x03, 0x88, 0x25, 0xb6, 0x8d, 0xa5, 0x16, 0x79, 0xd9, 0x2b,
	0xdf, 0xb5, 0x85, 0xd5, 0xc8, 0xb2, 0xa1, 0xdc, 0x23, 0xe2, 0x16, 0x4e, 0xbc, 0xf5, 0xaa, 0xde,
	0x3a, 0x45, 0x6d, 0x85, 0x6e, 0x6b, 0xde, 0x91, 0x8d, 0x84, 0x72, 0x3a, 0x10, 0x37, 0x70, 0xcc,
	0xb0, 0xe8, 0x2d, 0x6e, 0xcc, 0x07, 0xb2, 0xb9, 0x50, 0x4e, 0xf8, 0xbd, 0x84, 0x48, 0x72, 0xe2,
	0xe2, 0x0a, 0x0e, 0x65, 0x47, 0x3f, 0x71, 0x27, 0xf9, 0x58, 0x9e, 0x27, 0xf9, 0x68, 0x34, 0xfb,
	0x27, 0x2e, 0x21, 0x7e, 0xd4, 0xba, 0x4f, 0x29, 0xca, 0xf9, 0xfd, 0xb5, 0xb0, 0x0a, 0x5e, 0x22,
	0xfe, 0xbc, 0x87, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x84, 0xac, 0xab, 0x79, 0xd9, 0x01, 0x00,
	0x00,
}
